"""
Export functionality for reports in various formats.
"""
import csv
import io
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from datetime import datetime


class ExcelExporter:
    """Export reports to Excel format using openpyxl."""

    def export(self, report_data):
        """
        Export report data to Excel format.

        Args:
            report_data: Dictionary containing the report data

        Returns:
            BytesIO object containing the Excel file
        """
        wb = Workbook()
        wb.remove(wb.active)  # Remove default sheet

        # Create summary sheet
        self._create_summary_sheet(wb, report_data)

        # Create sheets for each section
        if 'sections' in report_data:
            for section_name, section_data in report_data['sections'].items():
                if isinstance(section_data, list) and section_data:
                    self._create_section_sheet(wb, section_name, section_data)
                elif isinstance(section_data, dict):
                    # For nested data like asset inventory
                    for subsection_name, subsection_data in section_data.items():
                        if isinstance(subsection_data, list) and subsection_data:
                            self._create_section_sheet(
                                wb,
                                f"{section_name}_{subsection_name}",
                                subsection_data
                            )

        # Special handling for asset inventory and software license reports
        if report_data.get('report_type') == 'asset_inventory' and 'assets' in report_data:
            for asset_type, assets in report_data['assets'].items():
                if assets:
                    self._create_section_sheet(wb, asset_type, assets)

        if report_data.get('report_type') == 'software_license' and 'licenses' in report_data:
            self._create_section_sheet(wb, 'licenses', report_data['licenses'])

        # Save to BytesIO
        excel_file = io.BytesIO()
        wb.save(excel_file)
        excel_file.seek(0)
        return excel_file.getvalue()

    def _create_summary_sheet(self, wb, report_data):
        """Create a summary sheet with report metadata."""
        ws = wb.create_sheet('Summary', 0)

        # Header styling
        header_font = Font(bold=True, size=14, color='FFFFFF')
        header_fill = PatternFill(start_color='366092', end_color='366092', fill_type='solid')

        # Add report metadata
        ws['A1'] = 'Report Summary'
        ws['A1'].font = header_font
        ws['A1'].fill = header_fill
        ws.merge_cells('A1:B1')

        row = 3
        ws[f'A{row}'] = 'Report Type:'
        ws[f'B{row}'] = report_data.get('report_type', 'N/A').replace('_', ' ').title()
        ws[f'A{row}'].font = Font(bold=True)

        row += 1
        ws[f'A{row}'] = 'Generated At:'
        ws[f'B{row}'] = report_data.get('generated_at', 'N/A')
        ws[f'A{row}'].font = Font(bold=True)

        row += 1
        ws[f'A{row}'] = 'Generated By:'
        ws[f'B{row}'] = report_data.get('generated_by', 'N/A')
        ws[f'A{row}'].font = Font(bold=True)

        # Add organization/location info if present
        if 'organization' in report_data:
            row += 2
            ws[f'A{row}'] = 'Organization:'
            ws[f'A{row}'].font = Font(bold=True, size=12)
            row += 1
            org = report_data['organization']
            ws[f'A{row}'] = 'Name:'
            ws[f'B{row}'] = org.get('name', 'N/A')
            ws[f'A{row}'].font = Font(bold=True)

        if 'location' in report_data:
            row += 2
            ws[f'A{row}'] = 'Location:'
            ws[f'A{row}'].font = Font(bold=True, size=12)
            row += 1
            loc = report_data['location']
            ws[f'A{row}'] = 'Name:'
            ws[f'B{row}'] = loc.get('name', 'N/A')
            ws[f'A{row}'].font = Font(bold=True)

        # Add summary statistics if present
        if 'summary' in report_data:
            row += 2
            ws[f'A{row}'] = 'Summary Statistics:'
            ws[f'A{row}'].font = Font(bold=True, size=12)
            row += 1

            for key, value in report_data['summary'].items():
                ws[f'A{row}'] = key.replace('_', ' ').title() + ':'
                ws[f'B{row}'] = value
                ws[f'A{row}'].font = Font(bold=True)
                row += 1

        # Adjust column widths
        ws.column_dimensions['A'].width = 25
        ws.column_dimensions['B'].width = 40

    def _create_section_sheet(self, wb, section_name, section_data):
        """Create a sheet for a specific section of data."""
        # Clean up sheet name (Excel has 31 char limit)
        sheet_name = section_name.replace('_', ' ').title()[:31]
        ws = wb.create_sheet(sheet_name)

        if not section_data:
            return

        # Get headers from first item
        headers = list(section_data[0].keys())

        # Header styling
        header_font = Font(bold=True, color='FFFFFF')
        header_fill = PatternFill(start_color='366092', end_color='366092', fill_type='solid')
        header_alignment = Alignment(horizontal='center', vertical='center')

        # Write headers
        for col_idx, header in enumerate(headers, start=1):
            cell = ws.cell(row=1, column=col_idx)
            cell.value = header.replace('_', ' ').title()
            cell.font = header_font
            cell.fill = header_fill
            cell.alignment = header_alignment

        # Write data
        for row_idx, item in enumerate(section_data, start=2):
            for col_idx, header in enumerate(headers, start=1):
                value = item.get(header, '')
                # Handle nested objects
                if isinstance(value, (dict, list)):
                    value = str(value)
                ws.cell(row=row_idx, column=col_idx, value=value)

        # Auto-adjust column widths
        for col_idx, header in enumerate(headers, start=1):
            max_length = len(header)
            for row_idx in range(2, len(section_data) + 2):
                cell_value = str(ws.cell(row=row_idx, column=col_idx).value)
                max_length = max(max_length, len(cell_value))
            ws.column_dimensions[chr(64 + col_idx)].width = min(max_length + 2, 50)

        # Add filters
        ws.auto_filter.ref = ws.dimensions


class CSVExporter:
    """Export reports to CSV format."""

    def export(self, report_data):
        """
        Export report data to CSV format.

        Args:
            report_data: Dictionary containing the report data

        Returns:
            String containing the CSV data
        """
        output = io.StringIO()
        writer = csv.writer(output)

        # Write metadata
        writer.writerow(['Report Type', report_data.get('report_type', 'N/A').replace('_', ' ').title()])
        writer.writerow(['Generated At', report_data.get('generated_at', 'N/A')])
        writer.writerow(['Generated By', report_data.get('generated_by', 'N/A')])
        writer.writerow([])

        # Write organization/location info if present
        if 'organization' in report_data:
            writer.writerow(['Organization', report_data['organization'].get('name', 'N/A')])
            writer.writerow([])

        if 'location' in report_data:
            writer.writerow(['Location', report_data['location'].get('name', 'N/A')])
            writer.writerow([])

        # Write main data sections
        if 'sections' in report_data:
            for section_name, section_data in report_data['sections'].items():
                if isinstance(section_data, list) and section_data:
                    self._write_section(writer, section_name, section_data)

        # Special handling for asset inventory
        if report_data.get('report_type') == 'asset_inventory' and 'assets' in report_data:
            for asset_type, assets in report_data['assets'].items():
                if assets:
                    self._write_section(writer, asset_type, assets)

        # Special handling for software licenses
        if report_data.get('report_type') == 'software_license' and 'licenses' in report_data:
            self._write_section(writer, 'licenses', report_data['licenses'])

        # Write summary if present
        if 'summary' in report_data:
            writer.writerow([])
            writer.writerow(['Summary Statistics'])
            for key, value in report_data['summary'].items():
                writer.writerow([key.replace('_', ' ').title(), value])

        csv_content = output.getvalue()
        output.close()
        return csv_content

    def _write_section(self, writer, section_name, section_data):
        """Write a section of data to CSV."""
        writer.writerow([])
        writer.writerow([section_name.replace('_', ' ').title()])
        writer.writerow([])

        if not section_data:
            return

        # Get headers from first item
        headers = list(section_data[0].keys())
        writer.writerow([h.replace('_', ' ').title() for h in headers])

        # Write data rows
        for item in section_data:
            row = []
            for header in headers:
                value = item.get(header, '')
                # Handle nested objects
                if isinstance(value, (dict, list)):
                    value = str(value)
                row.append(value)
            writer.writerow(row)


class PDFExporter:
    """Export reports to PDF format using ReportLab."""

    def export(self, report_data):
        """
        Export report data to PDF format.

        Args:
            report_data: Dictionary containing the report data

        Returns:
            BytesIO object containing the PDF file
        """
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=0.5*inch,
            leftMargin=0.5*inch,
            topMargin=0.75*inch,
            bottomMargin=0.5*inch
        )

        # Container for PDF elements
        elements = []
        styles = getSampleStyleSheet()

        # Custom styles
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#366092'),
            spaceAfter=30,
            alignment=TA_CENTER
        )

        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#366092'),
            spaceAfter=12,
            spaceBefore=12
        )

        # Title
        title = f"{report_data.get('report_type', 'Report').replace('_', ' ').title()}"
        elements.append(Paragraph(title, title_style))
        elements.append(Spacer(1, 0.2*inch))

        # Metadata table with proper text wrapping
        metadata_style = ParagraphStyle(
            'MetadataStyle',
            fontSize=10,
            leading=12,
            wordWrap='CJK',
            alignment=TA_LEFT,
        )

        metadata_style_bold = ParagraphStyle(
            'MetadataStyleBold',
            fontSize=10,
            leading=12,
            fontName='Helvetica-Bold',
            wordWrap='CJK',
            alignment=TA_LEFT,
        )

        metadata = [
            [Paragraph('Generated At:', metadata_style_bold),
             Paragraph(report_data.get('generated_at', 'N/A'), metadata_style)],
            [Paragraph('Generated By:', metadata_style_bold),
             Paragraph(report_data.get('generated_by', 'N/A'), metadata_style)],
        ]

        if 'organization' in report_data:
            metadata.append([
                Paragraph('Organization:', metadata_style_bold),
                Paragraph(report_data['organization'].get('name', 'N/A'), metadata_style)
            ])

        if 'location' in report_data:
            metadata.append([
                Paragraph('Location:', metadata_style_bold),
                Paragraph(report_data['location'].get('name', 'N/A'), metadata_style)
            ])

        metadata_table = Table(metadata, colWidths=[2*inch, 5*inch])
        metadata_table.setStyle(TableStyle([
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
        ]))
        elements.append(metadata_table)
        elements.append(Spacer(1, 0.3*inch))

        # Summary statistics
        if 'summary' in report_data and report_data['summary']:
            elements.append(Paragraph('Summary Statistics', heading_style))

            # Create style for summary table cells
            summary_cell_style = ParagraphStyle(
                'SummaryCellStyle',
                fontSize=10,
                leading=12,
                wordWrap='CJK',
                alignment=TA_LEFT,
                leftIndent=2,
                rightIndent=2,
            )

            summary_data = []
            for k, v in report_data['summary'].items():
                row = [
                    Paragraph(k.replace('_', ' ').title(), summary_cell_style),
                    Paragraph(str(v), summary_cell_style)
                ]
                summary_data.append(row)

            summary_table = Table(summary_data, colWidths=[4*inch, 2*inch])
            summary_table.setStyle(TableStyle([
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
                ('TOPPADDING', (0, 0), (-1, -1), 10),
                ('LEFTPADDING', (0, 0), (-1, -1), 8),
                ('RIGHTPADDING', (0, 0), (-1, -1), 8),
                ('GRID', (0, 0), (-1, -1), 1, colors.grey),
                ('ROWBACKGROUNDS', (0, 0), (-1, -1), [colors.white, colors.HexColor('#f0f0f0')]),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ]))
            elements.append(summary_table)
            elements.append(Spacer(1, 0.3*inch))

        # Add sections
        if 'sections' in report_data:
            for section_name, section_data in report_data['sections'].items():
                if isinstance(section_data, list) and section_data:
                    self._add_section_to_pdf(
                        elements,
                        section_name.replace('_', ' ').title(),
                        section_data,
                        heading_style
                    )

        # Special handling for asset inventory
        if report_data.get('report_type') == 'asset_inventory' and 'assets' in report_data:
            for asset_type, assets in report_data['assets'].items():
                if assets:
                    self._add_section_to_pdf(
                        elements,
                        asset_type.replace('_', ' ').title(),
                        assets,
                        heading_style
                    )

        # Special handling for software licenses
        if report_data.get('report_type') == 'software_license' and 'licenses' in report_data:
            self._add_section_to_pdf(
                elements,
                'Software Licenses',
                report_data['licenses'],
                heading_style
            )

        # Build PDF
        doc.build(elements)
        buffer.seek(0)
        return buffer.getvalue()

    def _add_section_to_pdf(self, elements, section_title, section_data, heading_style):
        """Add a section of data to the PDF."""
        if not section_data:
            return

        elements.append(PageBreak())
        elements.append(Paragraph(section_title, heading_style))
        elements.append(Spacer(1, 0.2*inch))

        # Get headers (exclude 'id' field and limit to first 6 for readability in PDF)
        all_headers = [h for h in section_data[0].keys() if h.lower() != 'id']
        headers = all_headers[:6] if len(all_headers) > 6 else all_headers

        # Create a style for table cells with wrapping
        cell_style = ParagraphStyle(
            'CellStyle',
            fontSize=9,
            leading=11,  # Line spacing
            wordWrap='CJK',  # Enable word wrapping
            alignment=TA_LEFT,
            leftIndent=2,
            rightIndent=2,
            spaceAfter=0,
            spaceBefore=0,
        )

        header_cell_style = ParagraphStyle(
            'HeaderCellStyle',
            fontSize=10,
            leading=12,
            fontName='Helvetica-Bold',
            wordWrap='CJK',
            alignment=TA_LEFT,
            leftIndent=2,
            rightIndent=2,
            textColor=colors.whitesmoke,
        )

        # Prepare table data with Paragraph objects for word wrapping
        table_data = []

        # Header row
        header_row = []
        for h in headers:
            header_row.append(Paragraph(h.replace('_', ' ').title(), header_cell_style))
        table_data.append(header_row)

        # Data rows
        for item in section_data:
            row = []
            for header in headers:
                value = item.get(header, '')
                # Handle nested objects and None values
                if isinstance(value, (dict, list)):
                    value = 'Complex Data'
                elif value is None:
                    value = ''
                else:
                    value = str(value)

                # Use Paragraph for automatic text wrapping
                row.append(Paragraph(value, cell_style))
            table_data.append(row)

        # Calculate column widths based on content
        available_width = 7 * inch
        col_width = available_width / len(headers)

        # Create table with dynamic row heights
        table = Table(table_data, colWidths=[col_width] * len(headers), repeatRows=1)
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#366092')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
            ('TOPPADDING', (0, 0), (-1, -1), 10),
            ('LEFTPADDING', (0, 0), (-1, -1), 6),
            ('RIGHTPADDING', (0, 0), (-1, -1), 6),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f0f0f0')]),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ]))

        elements.append(table)
        elements.append(Spacer(1, 0.3*inch))
