# Generated by Django 5.0.1 on 2025-11-26 11:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Device name or identifier', max_length=255)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('laptop', 'Laptop'), ('workstation', 'Workstation'), ('other', 'Other')], default='desktop', max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('cpu', models.CharField(blank=True, help_text='Processor details', max_length=255)),
                ('ram', models.CharField(blank=True, help_text='e.g., 16GB DDR4', max_length=100)),
                ('storage', models.CharField(blank=True, help_text='e.g., 512GB SSD', max_length=255)),
                ('gpu', models.CharField(blank=True, help_text='Graphics card details', max_length=255)),
                ('operating_system', models.CharField(blank=True, help_text='e.g., Windows 11 Pro', max_length=255)),
                ('software_installed', models.TextField(blank=True, help_text='Comma-separated list of installed software')),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('mac_address', models.CharField(blank=True, max_length=50)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_devices', to='core.contact')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endpoint_users', to='core.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoint_users', to='core.organization')),
            ],
            options={
                'db_table': 'endpoint_users',
                'ordering': ['organization', 'device_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('device_type', models.CharField(choices=[('firewall', 'Firewall'), ('router', 'Router'), ('firewall_router', 'Firewall/Router'), ('switch', 'Switch'), ('wifi', 'WiFi Access Point'), ('other', 'Other')], default='other', max_length=50)),
                ('internet_provider', models.CharField(blank=True, max_length=255)),
                ('internet_speed', models.CharField(blank=True, help_text='e.g., 100/100 Mbps', max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('mac_address', models.CharField(blank=True, max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('firmware_version', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_devices', to='core.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_devices', to='core.organization')),
            ],
            options={
                'db_table': 'network_devices',
                'ordering': ['organization', 'device_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Peripheral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('device_type', models.CharField(choices=[('printer', 'Printer'), ('scanner', 'Scanner'), ('multifunction', 'Multifunction Printer'), ('ups', 'UPS'), ('nas', 'NAS'), ('other', 'Other')], default='printer', max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('mac_address', models.CharField(blank=True, max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peripherals', to='core.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peripherals', to='core.organization')),
            ],
            options={
                'db_table': 'peripherals',
                'ordering': ['organization', 'device_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('server_type', models.CharField(choices=[('physical', 'Physical Server'), ('virtual', 'Virtual Machine'), ('cloud', 'Cloud Instance'), ('container', 'Container'), ('other', 'Other')], default='physical', max_length=50)),
                ('role', models.CharField(blank=True, help_text='e.g., Web Server, Database, File Server', max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('cpu', models.CharField(blank=True, help_text='Processor details', max_length=255)),
                ('ram', models.CharField(blank=True, help_text='e.g., 64GB DDR4', max_length=100)),
                ('storage', models.CharField(blank=True, help_text='e.g., 2TB SSD RAID 10', max_length=255)),
                ('operating_system', models.CharField(blank=True, help_text='e.g., Ubuntu 22.04 LTS', max_length=255)),
                ('software_installed', models.TextField(blank=True, help_text='Comma-separated list of installed software')),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('mac_address', models.CharField(blank=True, max_length=50)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to='core.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='core.organization')),
            ],
            options={
                'db_table': 'servers',
                'ordering': ['organization', 'server_type', 'name'],
            },
        ),
    ]
