# Generated by Django 5.0.1 on 2025-11-27 13:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_configuration_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(help_text='Backup solution name or identifier', max_length=255)),
                ('backup_type', models.CharField(choices=[('server', 'Server Backup'), ('microsoft365', 'Microsoft 365 Backup'), ('cloud', 'Cloud Backup'), ('endpoint', 'Endpoint Backup'), ('database', 'Database Backup'), ('nas', 'NAS Backup'), ('other', 'Other')], default='other', max_length=50)),
                ('vendor', models.CharField(blank=True, help_text='Backup solution vendor', max_length=255)),
                ('frequency', models.CharField(blank=True, help_text='e.g., Daily, Hourly, Weekly', max_length=100)),
                ('retention_period', models.CharField(blank=True, help_text='e.g., 30 days, 1 year', max_length=100)),
                ('storage_location', models.CharField(blank=True, help_text='Where backups are stored', max_length=255)),
                ('storage_capacity', models.CharField(blank=True, help_text='e.g., 500GB, 2TB', max_length=100)),
                ('target_systems', models.TextField(blank=True, help_text='Systems or data being backed up')),
                ('last_backup_date', models.DateTimeField(blank=True, help_text='Last successful backup', null=True)),
                ('next_backup_date', models.DateTimeField(blank=True, help_text='Next scheduled backup', null=True)),
                ('backup_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('failed', 'Failed'), ('warning', 'Warning')], default='active', max_length=50)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly or annual cost', max_digits=10, null=True)),
                ('cost_period', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('one_time', 'One-time')], default='monthly', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to='core.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='core.organization')),
            ],
            options={
                'db_table': 'backups',
                'ordering': ['organization', 'backup_type', 'name'],
            },
        ),
    ]
