# Generated by Django 5.0.1

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_software_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoIP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(help_text='VoIP service name or product', max_length=255)),
                ('voip_type', models.CharField(choices=[('teams', 'Microsoft Teams'), ('zoom', 'Zoom Phone'), ('ringcentral', 'RingCentral'), ('8x8', '8x8'), ('vonage', 'Vonage'), ('cisco', 'Cisco WebEx'), ('other', 'Other')], default='other', max_length=50)),
                ('license_key', models.CharField(blank=True, help_text='License code or account ID', max_length=255)),
                ('version', models.CharField(blank=True, help_text='e.g., Business, Enterprise, Pro', max_length=100)),
                ('license_type', models.CharField(choices=[('perpetual', 'Perpetual'), ('subscription', 'Subscription'), ('trial', 'Trial'), ('free', 'Free'), ('other', 'Other')], default='subscription', max_length=50)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='License expiration date', null=True)),
                ('vendor', models.CharField(blank=True, help_text='VoIP vendor or service provider', max_length=255)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='License cost per unit', max_digits=10, null=True)),
                ('quantity', models.IntegerField(default=1, help_text='Number of licenses/extensions')),
                ('phone_numbers', models.TextField(blank=True, help_text='Associated phone numbers (comma-separated)')),
                ('extensions', models.TextField(blank=True, help_text='Extension numbers (comma-separated)')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voip', to='core.organization')),
            ],
            options={
                'db_table': 'voip',
                'ordering': ['organization', 'voip_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VoIPAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('extension', models.CharField(blank=True, help_text='Assigned extension number', max_length=50)),
                ('phone_number', models.CharField(blank=True, help_text='Assigned phone number', max_length=50)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voip_assignments', to='core.contact')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('voip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voip_assignments', to='core.voip')),
            ],
            options={
                'db_table': 'voip_assignments',
                'unique_together': {('voip', 'contact')},
            },
        ),
    ]
