# Generated by Django 5.0.1

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_voip_voip_type_organizationmember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternetConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('provider_name', models.CharField(max_length=255)),
                ('connection_type', models.CharField(
                    choices=[
                        ('fiber', 'Fiber'),
                        ('cable', 'Cable'),
                        ('dsl', 'DSL'),
                        ('wireless', '5G/Wireless'),
                        ('satellite', 'Satellite'),
                        ('other', 'Other'),
                    ],
                    default='fiber',
                    max_length=50
                )),
                ('download_speed', models.PositiveIntegerField(help_text='Download speed in Mbps')),
                ('upload_speed', models.PositiveIntegerField(help_text='Upload speed in Mbps')),
                ('is_primary', models.BooleanField(default=True, help_text='Primary connection for failover')),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='%(class)s_created',
                    to=settings.AUTH_USER_MODEL
                )),
                ('deleted_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='%(class)s_deleted',
                    to=settings.AUTH_USER_MODEL
                )),
                ('network_device', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='internet_connections',
                    to='core.networkdevice'
                )),
            ],
            options={
                'db_table': 'internet_connections',
                'ordering': ['network_device', '-is_primary', 'provider_name'],
            },
        ),
    ]
