# Generated by Django 5.0.1 on 2026-03-10 07:08

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0013_server_storage_and_host_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(help_text='UUID of the entity being versioned', max_length=36)),
                ('version_number', models.IntegerField(help_text='Sequential version number for this entity')),
                ('change_note', models.TextField(blank=True, help_text='Optional description of what changed in this version')),
                ('snapshot', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Complete serialized state of the entity at this version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(help_text='The type of entity being versioned', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_versions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'entity_versions',
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='entity_vers_content_ef9123_idx'), models.Index(fields=['created_at'], name='entity_vers_created_964abe_idx')],
                'unique_together': {('content_type', 'object_id', 'version_number')},
            },
        ),
    ]
