# Generated by Django 5.0.1 on 2026-03-12 13:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_entityversion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("restore", "Restore"),
                            ("export", "Export"),
                            ("import", "Import"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True,
                        help_text="Model name, e.g. 'Organization', 'Documentation'",
                        max_length=100,
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Primary key of the affected object",
                        max_length=255,
                    ),
                ),
                (
                    "entity_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human-readable name/title of the affected object",
                        max_length=255,
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Organization the entity belongs to, if applicable",
                        max_length=255,
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional details about the action",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp", "action"],
                        name="audit_log_timesta_d9c65d_idx",
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="audit_log_user_id_79f582_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "-timestamp"],
                        name="audit_log_entity__98a8b9_idx",
                    ),
                ],
            },
        ),
    ]
